"""Turn Bruno's bleat into a C array at build time.

    extra_scripts = pre:scripts/embed_wav.py

WHY A GENERATOR RATHER THAN A COMMITTED HEADER

The design called for `xxd -i` and a ~390KB header in the tree, "ugly in a
diff and cheap at compile time". Generating it instead costs the same at
compile time and keeps the `.wav` as the single source of truth. A committed
array is a second copy of the same bytes, and two copies of anything in this
project have a habit of drifting - the frame constants needed a conformance
test for exactly that reason, and `SHEPHERD_WORST_FRAME` had to stop repeating
a number that was written in two places.

It also means editing the sound is editing the sound, not editing the sound
and then remembering to regenerate something.

WHY THE WHOLE FILE, HEADER AND ALL

`M5Unified`'s `Speaker_Class::playWav` takes the complete RIFF file, walks the
sub-chunks looking for `data`, and clamps playback to that chunk's length. So
passing `sizeof(array)` plays exactly the audio and not the header. That
matters here because this particular file carries a `LIST` chunk between
`fmt ` and `data` - 26 bytes of metadata that a lazier parser would emit as a
burst of static before the bleat.

The validation below is deliberately loud. A wav that is not PCM, or is not
the format this was verified against, should fail the BUILD rather than
produce a firmware that plays noise into a room.
"""

import struct
from pathlib import Path

Import("env")  # noqa: F821

ASSET = Path(env.subst("$PROJECT_DIR")) / "assets" / "bruno" / "baa.wav"  # noqa: F821
OUT_DIR = Path(env.subst("$BUILD_DIR")) / "generated"  # noqa: F821
OUT = OUT_DIR / "baa_wav.h"

# WAVE_FORMAT_PCM. Anything else (IEEE float, ADPCM, an mp3-in-riff) would
# need a decoder M5Unified does not have.
PCM = 1


def parse_wav(raw: bytes) -> dict:
    """Read the format off the file rather than trusting its extension."""
    if raw[:4] != b"RIFF" or raw[8:12] != b"WAVE":
        raise ValueError("not a RIFF/WAVE file")

    info, pos = {}, 12
    chunks = []
    while pos + 8 <= len(raw):
        cid = raw[pos:pos + 4]
        size = struct.unpack_from("<I", raw, pos + 4)[0]
        chunks.append((cid.decode("ascii", "replace"), size))
        body = raw[pos + 8:pos + 8 + size]
        if cid == b"fmt " and size >= 16:
            fmt, ch, rate, _bps, _align, bits = struct.unpack_from("<HHIIHH", body)
            info.update(codec=fmt, channels=ch, rate=rate, bits=bits)
        elif cid == b"data":
            info["data_bytes"] = size
        pos += 8 + size + (size & 1)      # chunks are word-aligned
    info["chunks"] = chunks
    return info


def main() -> None:
    if not ASSET.exists():
        raise SystemExit(f"embed_wav: {ASSET} is missing")

    raw = ASSET.read_bytes()
    info = parse_wav(raw)

    if info.get("codec") != PCM:
        raise SystemExit(
            f"embed_wav: {ASSET.name} is codec {info.get('codec')}, not PCM. "
            f"M5Unified's playWav has no decoder - re-export as PCM."
        )
    seconds = info["data_bytes"] / (info["rate"] * info["channels"] * info["bits"] // 8)
    print(f"embed_wav: {ASSET.name} PCM {info['channels']}ch "
          f"{info['rate']}Hz {info['bits']}-bit, {info['data_bytes']} bytes "
          f"of audio ({seconds:.2f}s), chunks={[c for c, _ in info['chunks']]}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    body = []
    for i in range(0, len(raw), 16):
        row = ", ".join(f"0x{b:02x}" for b in raw[i:i + 16])
        body.append(f"  {row},")

    OUT.write_text(
        "// GENERATED by scripts/embed_wav.py - do not edit.\n"
        f"// Source: assets/bruno/{ASSET.name}\n"
        f"// PCM {info['channels']}ch {info['rate']}Hz {info['bits']}-bit, "
        f"{seconds:.2f}s of audio in {len(raw)} bytes of file.\n"
        "//\n"
        "// The WHOLE file, header and all: playWav walks the sub-chunks for\n"
        "// `data` and clamps to its length, so passing sizeof() plays the\n"
        "// audio and not the header. This file has a LIST chunk between\n"
        "// `fmt ` and `data` that a lazier parser would play as static.\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "alignas(4) static const uint8_t baa_wav[] = {\n"
        + "\n".join(body)
        + "\n};\n",
        encoding="utf-8",
    )
    print(f"embed_wav: wrote {OUT} ({OUT.stat().st_size} bytes of source)")
    env.Append(CPPPATH=[str(OUT_DIR)])  # noqa: F821


main()
